esphome:
  name: esp32-spa
  friendly_name: esp32-spa

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Spa Fallback Hotspot"
    password: !secret ap_password

captive_portal:

external_components:
  - source: esp32-spa
  
logger:
  level: DEBUG
  baud_rate: 0   # Prevent UART timing issues

# ===== HOT TUB DISPLAY INPUTS =====
sensor:
  - platform: inputs
    id: display_handler
    measured_temp:
      name: "Spa Measured Temp"
      id: spa_measured_temp
      unit_of_measurement: "°F"
      accuracy_decimals: 0
      device_class: temperature
    set_temp:
      name: "Spa Set Temp"
      id: spa_set_temp
      unit_of_measurement: "°F"
      accuracy_decimals: 0
      device_class: temperature

binary_sensor:
  - platform: inputs
    parent_id: display_handler
    type: heater
    name: "Spa Heater Status"
  - platform: inputs
    parent_id: display_handler
    type: pump
    name: "Spa Pump Status"
  - platform: inputs
    parent_id: display_handler
    type: light
    name: "Spa Light Status"

# ===== BUTTONS (GPIO outputs) =====
output:
  - platform: gpio
    id: spa_warm_out
    pin: 25
    inverted: false
  - platform: gpio
    id: spa_cool_out
    pin: 26
    inverted: false
  - platform: gpio
    id: spa_lights_out
    pin: 27
    inverted: false
  - platform: gpio
    id: spa_pumps_out
    pin: 32
    inverted: false

button:
  - platform: template
    name: "Spa Warm"
    icon: "mdi:thermometer-plus"
    on_press:
      - output.turn_on: spa_warm_out
      - delay: 100ms
      - output.turn_off: spa_warm_out

  - platform: template
    name: "Spa Cool"
    icon: "mdi:thermometer-minus"
    on_press:
      - output.turn_on: spa_cool_out
      - delay: 100ms
      - output.turn_off: spa_cool_out

  - platform: template
    name: "Spa Lights"
    icon: "mdi:lightbulb"
    on_press:
      - output.turn_on: spa_lights_out
      - delay: 100ms
      - output.turn_off: spa_lights_out

  - platform: template
    name: "Spa Pumps"
    icon: "mdi:pump"
    on_press:
      - output.turn_on: spa_pumps_out
      - delay: 100ms
      - output.turn_off: spa_pumps_out

# ===== DEBUG TOGGLE SWITCH =====
switch:
  - platform: template
    name: "Hot Tub Display Debug Logging"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: |-
          id(display_handler)->set_debug(true);
    turn_off_action:
      - lambda: |-
          id(display_handler)->set_debug(false);